name: picbook
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  state_notifier: ^0.7.2+1
  json_annotation: ^4.6.0
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  webview_flutter: ^3.0.4
  analyzer: ^4.3.1
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0 
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  network_image_mock: ^2.1.1

dependency_overrides:
  code_builder: ^4.2.0

flutter:
  uses-material-design: true
