name: picbook
description: A new Flutter project.

version: 1.0.2+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.1.0
  state_notifier: ^0.7.2+1
  json_annotation: ^4.6.0
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  flutter_staggered_grid_view: ^0.6.2
  webview_flutter: ^3.0.4
  analyzer: ^4.3.1
  http: ^0.13.5
  skeleton_text: ^3.0.0
  image_network: ^2.5.1
  hexcolor: ^2.0.7
  mobile_scanner: ^2.0.0
  logger: ^1.1.0
  firebase_analytics: ^9.3.1
  age_calculator: ^1.0.0
  intl: ^0.17.0
  firebase_crashlytics: ^2.8.8
  table_calendar: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0 
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_lints: ^2.0.0
  mockito: ^5.0.0
  network_image_mock: ^2.1.1
  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true 
  ios: false
  image_path: "lib/assets/images/icon.png"

dependency_overrides:
  code_builder: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/splash.png
