// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1KJABON0O2ll8fLIBHkjkO5gqTlAMHnY',
    appId: '1:485375588972:web:05a88277ff53e6d9d47649',
    messagingSenderId: '485375588972',
    projectId: 'pj-picbook-pro',
    authDomain: 'pj-picbook-pro.firebaseapp.com',
    storageBucket: 'pj-picbook-pro.appspot.com',
    measurementId: 'G-WQ3WKG8LY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz0udbUmMWFA1SGKrPgduAvYfDBwRqU5s',
    appId: '1:485375588972:android:d954da5cc6d59a96d47649',
    messagingSenderId: '485375588972',
    projectId: 'pj-picbook-pro',
    storageBucket: 'pj-picbook-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCp82rVJmoiDsj0Rvp6cZ5bF6aXRA6nY',
    appId: '1:485375588972:ios:fd2f17975baa0ea4d47649',
    messagingSenderId: '485375588972',
    projectId: 'pj-picbook-pro',
    storageBucket: 'pj-picbook-pro.appspot.com',
    iosClientId: '485375588972-bl9lumbgc9ddesh59itdpd9oqggj2ulp.apps.googleusercontent.com',
    iosBundleId: 'com.example.picbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCp82rVJmoiDsj0Rvp6cZ5bF6aXRA6nY',
    appId: '1:485375588972:ios:fd2f17975baa0ea4d47649',
    messagingSenderId: '485375588972',
    projectId: 'pj-picbook-pro',
    storageBucket: 'pj-picbook-pro.appspot.com',
    iosClientId: '485375588972-bl9lumbgc9ddesh59itdpd9oqggj2ulp.apps.googleusercontent.com',
    iosBundleId: 'com.example.picbook',
  );
}
