User:
  id: string # firebase authentication uid = users collection documentId
  name: string
  email: string
  linkedAccount: string ( Google | Apple )
Book:
  id: string # firestore documentId
  title: string
  isbn: string
  titleKana: string
  subTitle: string
  subTitleKana: string
  seriesName: string
  seriesNameKana: string
  contents: string
  contentsKana: string
  author: string
  authorKana: string
  publisherName: string
  size: string
  itemCaption: string 
  salesDate: string
  itemPrice: int
  itemUrl: string
  affiliateUrl: string
  smallImageUrl: string
  mediumImageUrl: string
  largeImageUrl: string
  chirayomiUrl: string
  availability: string
  postageFlag: string
  limitedFlag: string
  reviewCount: string
  reviewAverage: string
  booksGenreId: string
  registeredDateTime: DateTime
  history: DateTime[]
BookshelfHistory:
  date: DateTime
  book: Book
Bookshelf:
  id: string
  owner: string
  ownerBirthday: DateTime
  books: Book[]
  readHistories: BookshelfHistory[]
  created: DateTime

  