User:
  id: string
  name: string
  email: string
  linkedAccount: string ( Google | Apple )
  bookshelfs: Bookshelf[]
Book:
  id: string
  title: string
  titleKana: string
  subTitle: string
  subTitleKana: string
  author: string
  authorKana: string
  itemCaption: string
  isbn: string
  itemPrice: string
  itemUrl: string
  largeImageUrl: string
  mediumImageUrl: string
  publisherName: string
  salesDate: string
  size: string
  smallImageUrl: string
RegisteredBook:
  id: string
  book: Book
  registeredDateTime: DateTime
  history: DateTime[]
Bookshelf:
  id: string
  name: string
  books: RegisteredBook[]
  readHistories: ReadHistory[]
  created: DateTime
BookshelfHistory:
  date: DateTime
  book: RegisteredBook
  